.TH "include/ResourceManager.h" 3 "Fri May 6 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ResourceManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <raylib\&.h>\fP
.br
\fC#include 'uthash/uthash\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fB__Resource_u\fP"
.br
.RI "The Resource data union (all the possible resource data types) "
.ti -1c
.RI "struct \fB__Resource_t\fP"
.br
.RI "The Resource Data Structure: "
.ti -1c
.RI "struct \fB__ResourceManager_t\fP"
.br
.RI "The resource object structure\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRESOURCE_MANAGER_SUCCESS\fP   0"
.br
.ti -1c
.RI "#define \fBRESOURCE_MANAGER_WARNING\fP   1"
.br
.ti -1c
.RI "#define \fBRESOURCE_MANAGER_ERROR\fP   2"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBResourceType\fP { \fBRESOURCE_IMAGE\fP, \fBRESOURCE_TEXTURE2D\fP, \fBRESOURCE_FONT\fP, \fBRESOURCE_WAVE\fP, \fBRESOURCE_SOUND\fP, \fBRESOURCE_MUSIC\fP }"
.br
.RI "< "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fB__ResourceManagerGetResourceName\fP (\fBResourceType\fP type, const char *name)"
.br
.ti -1c
.RI "struct \fB__Resource_t\fP * \fB__ResourceManagerGetResourcePointer\fP (char *fullName)"
.br
.ti -1c
.RI "void * \fB__ResourceManagerGetResourceDataPointer\fP (struct \fB__Resource_t\fP *resource)"
.br
.ti -1c
.RI "int \fB__ResourceManagerInit\fP ()"
.br
.ti -1c
.RI "int \fB__ResourceManagerAddResource\fP (\fBResourceType\fP type, const char *name, const char *path)"
.br
.ti -1c
.RI "int \fB__ResourceManagerRemoveResource\fP (\fBResourceType\fP type, const char *name)"
.br
.ti -1c
.RI "int \fB__ResourceManagerLoad\fP ()"
.br
.ti -1c
.RI "void * \fB__ResourceManagerGet\fP (\fBResourceType\fP type, const char *name)"
.br
.ti -1c
.RI "int \fB__ResourceManagerUnload\fP ()"
.br
.ti -1c
.RI "int \fB__ResourceManagerDestroy\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RESOURCE_MANAGER_ERROR   2"

.SS "#define RESOURCE_MANAGER_SUCCESS   0"

.SS "#define RESOURCE_MANAGER_WARNING   1"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBResourceType\fP"

.PP
< 
.SH "stocazzo"
.PP
The resource Type: Image, Texture, Font, Wave, Sound, Music 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRESOURCE_IMAGE \fP\fP

.PP
\fBSee also\fP
.RS 4
Image 
.RE
.PP

.TP
\fB\fIRESOURCE_TEXTURE2D \fP\fP

.PP
\fBSee also\fP
.RS 4
Texture2D 
.RE
.PP

.TP
\fB\fIRESOURCE_FONT \fP\fP

.PP
\fBSee also\fP
.RS 4
Font 
.RE
.PP

.TP
\fB\fIRESOURCE_WAVE \fP\fP

.PP
\fBSee also\fP
.RS 4
Wave 
.RE
.PP

.TP
\fB\fIRESOURCE_SOUND \fP\fP

.PP
\fBSee also\fP
.RS 4
Sound 
.RE
.PP

.TP
\fB\fIRESOURCE_MUSIC \fP\fP

.PP
\fBSee also\fP
.RS 4
Music 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int __ResourceManagerAddResource (\fBResourceType\fP type, const char * name, const char * path)"

.PP
\fBParameters\fP
.RS 4
\fItype\fP 
.br
\fIname\fP 
.br
\fIpath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int RESOURCE_MANAGER_ERROR or RESOURCE_MANAGER_WARNING or RESOURCE_MANAGER_SUCCESS 
.RE
.PP

.SS "int __ResourceManagerDestroy ()"

.PP
\fBReturns\fP
.RS 4
int RESOURCE_MANAGER_ERROR or RESOURCE_MANAGER_WARNING or RESOURCE_MANAGER_SUCCESS 
.RE
.PP

.SS "void * __ResourceManagerGet (\fBResourceType\fP type, const char * name)"

.PP
\fBParameters\fP
.RS 4
\fItype\fP 
.br
\fIname\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void* 
.RE
.PP

.SS "void * __ResourceManagerGetResourceDataPointer (struct \fB__Resource_t\fP * resource)"

.SS "char * __ResourceManagerGetResourceName (\fBResourceType\fP type, const char * name)"

.SS "struct \fB__Resource_t\fP * __ResourceManagerGetResourcePointer (char * fullName)"

.SS "int __ResourceManagerInit ()"

.PP
\fBReturns\fP
.RS 4
int RESOURCE_MANAGER_ERROR or RESOURCE_MANAGER_WARNING or RESOURCE_MANAGER_SUCCESS 
.RE
.PP

.SS "int __ResourceManagerLoad ()"

.PP
\fBReturns\fP
.RS 4
int RESOURCE_MANAGER_ERROR or RESOURCE_MANAGER_WARNING or RESOURCE_MANAGER_SUCCESS 
.RE
.PP

.SS "int __ResourceManagerRemoveResource (\fBResourceType\fP type, const char * name)"

.PP
\fBParameters\fP
.RS 4
\fItype\fP 
.br
\fIname\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int RESOURCE_MANAGER_ERROR or RESOURCE_MANAGER_WARNING or RESOURCE_MANAGER_SUCCESS 
.RE
.PP

.SS "int __ResourceManagerUnload ()"

.PP
\fBReturns\fP
.RS 4
int RESOURCE_MANAGER_ERROR or RESOURCE_MANAGER_WARNING or RESOURCE_MANAGER_SUCCESS 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
