.TH "include/Scene/SceneSplashScreen.h" 3 "Fri May 6 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Scene/SceneSplashScreen.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SceneManager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSceneSplashScreenOnInit\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnStart\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnUpdate\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnFixedUpdate\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnRender\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnExit\fP (void **_$)"
.br
.ti -1c
.RI "\fBDefineScene\fP (SceneSplashScreen, 'SceneSplashScreen', SceneSplashScreenOnInit, \fBSceneSplashScreenOnStart\fP, \fBSceneSplashScreenOnUpdate\fP, \fBSceneSplashScreenOnFixedUpdate\fP, \fBSceneSplashScreenOnRender\fP, \fBSceneSplashScreenOnExit\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DefineScene (SceneSplashScreen, 'SceneSplashScreen', \fBSceneSplashScreenOnInit\fP, \fBSceneSplashScreenOnStart\fP, \fBSceneSplashScreenOnUpdate\fP, \fBSceneSplashScreenOnFixedUpdate\fP, \fBSceneSplashScreenOnRender\fP, \fBSceneSplashScreenOnExit\fP)"

.SS "void SceneSplashScreenOnExit (void ** _$)"

.SS "void SceneSplashScreenOnFixedUpdate (void ** _$)"

.SS "void SceneSplashScreenOnInit (void ** _$)"

.SS "void SceneSplashScreenOnRender (void ** _$)"

.SS "void SceneSplashScreenOnStart (void ** _$)"

.SS "void SceneSplashScreenOnUpdate (void ** _$)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
