.TH "SceneSplashScreenData" 3 "Fri May 6 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneSplashScreenData
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Texture2D \fBt\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "Texture2D SceneSplashScreenData::t"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
