.TH "source/Scene/SceneSplashScreen.c" 3 "Fri May 6 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/Scene/SceneSplashScreen.c
.SH SYNOPSIS
.br
.PP
\fC#include 'SceneManager\&.h'\fP
.br
\fC#include 'ResourceManager\&.h'\fP
.br
\fC#include 'Scene/SceneSplashScreen\&.h'\fP
.br
\fC#include <raylib\&.h>\fP
.br
\fC#include <raymath\&.h>\fP
.br
\fC#include 'raylib\-extra/raygui\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSceneSplashScreenData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSceneSplashScreenOnInit\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnStart\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnUpdate\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnFixedUpdate\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnRender\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneSplashScreenOnExit\fP (void **_$)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void SceneSplashScreenOnExit (void ** _$)"

.SS "void SceneSplashScreenOnFixedUpdate (void ** _$)"

.SS "void SceneSplashScreenOnInit (void ** _$)"

.SS "void SceneSplashScreenOnRender (void ** _$)"

.SS "void SceneSplashScreenOnStart (void ** _$)"

.SS "void SceneSplashScreenOnUpdate (void ** _$)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
