.TH "SceneManager_t" 3 "Fri May 6 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneManager_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SceneManager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBrunning\fP"
.br
.ti -1c
.RI "\fBScene\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "\fBScene\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBSceneManagerState\fP \fBstatus\fP"
.br
.ti -1c
.RI "float \fBfixedUpdateTimer\fP"
.br
.ti -1c
.RI "double \fBsceneInitTime\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBScene\fP* SceneManager_t::current"

.SS "float SceneManager_t::fixedUpdateTimer"

.SS "\fBScene\fP* SceneManager_t::next"

.SS "bool SceneManager_t::running"

.SS "double SceneManager_t::sceneInitTime"

.SS "\fBSceneManagerState\fP SceneManager_t::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
