.TH "include/external Directory Reference" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/external Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBexternal\fP"
.br
.ti -1c
.RI "directory \fButhash\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBraygui\&.h\fP"
.br
.in -1c
