.TH "AES_ctx" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AES_ctx
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRoundKey\fP [\fBAES_keyExpSize\fP]"
.br
.ti -1c
.RI "uint8_t \fBIv\fP [\fBAES_BLOCKLEN\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t AES_ctx::Iv[\fBAES_BLOCKLEN\fP]"

.SS "uint8_t AES_ctx::RoundKey[\fBAES_keyExpSize\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
