.TH "crypto_sign_vtable" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crypto_sign_vtable \- Type definitions ///\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monocypher\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBhash\fP )(uint8_t hash[64], const uint8_t *message, size_t message_size)"
.br
.ti -1c
.RI "void(* \fBinit\fP )(void *ctx)"
.br
.ti -1c
.RI "void(* \fBupdate\fP )(void *ctx, const uint8_t *message, size_t message_size)"
.br
.ti -1c
.RI "void(* \fBfinal\fP )(void *ctx, uint8_t \fBhash\fP[64])"
.br
.ti -1c
.RI "size_t \fBctx_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions ///\&. 
.SH "Field Documentation"
.PP 
.SS "size_t crypto_sign_vtable::ctx_size"

.SS "void(* crypto_sign_vtable::final) (void *ctx, uint8_t \fBhash\fP[64])"

.SS "void(* crypto_sign_vtable::hash) (uint8_t hash[64], const uint8_t *message, size_t message_size)"

.SS "void(* crypto_sign_vtable::init) (void *ctx)"

.SS "void(* crypto_sign_vtable::update) (void *ctx, const uint8_t *message, size_t message_size)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
