.TH "crypto_poly1305_ctx" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crypto_poly1305_ctx
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monocypher\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBr\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBh\fP [5]"
.br
.ti -1c
.RI "uint32_t \fBc\fP [5]"
.br
.ti -1c
.RI "uint32_t \fBpad\fP [4]"
.br
.ti -1c
.RI "size_t \fBc_idx\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t crypto_poly1305_ctx::c[5]"

.SS "size_t crypto_poly1305_ctx::c_idx"

.SS "uint32_t crypto_poly1305_ctx::h[5]"

.SS "uint32_t crypto_poly1305_ctx::pad[4]"

.SS "uint32_t crypto_poly1305_ctx::r[4]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
