.TH "GuiStyleProp" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GuiStyleProp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <raygui\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBcontrolId\fP"
.br
.ti -1c
.RI "unsigned short \fBpropertyId\fP"
.br
.ti -1c
.RI "int \fBpropertyValue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned short GuiStyleProp::controlId"

.SS "unsigned short GuiStyleProp::propertyId"

.SS "int GuiStyleProp::propertyValue"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
