.TH "source/utils/logger.c" 3 "Tue May 10 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/utils/logger.c
.SH SYNOPSIS
.br
.PP
\fC#include 'utils/logger\&.h'\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <raylib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLog\fP (int msgType, const char *text,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBLogVaList\fP (int msgType, const char *text, va_list args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Log (int msgType, const char * text,  \&.\&.\&.)"

.SS "void LogVaList (int msgType, const char * text, va_list args)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
