.TH "LZ4_stream_t_internal" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LZ4_stream_t_internal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lz4\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLZ4_u32\fP \fBhashTable\fP [\fBLZ4_HASH_SIZE_U32\fP]"
.br
.ti -1c
.RI "\fBLZ4_u32\fP \fBcurrentOffset\fP"
.br
.ti -1c
.RI "\fBLZ4_u32\fP \fBtableType\fP"
.br
.ti -1c
.RI "const \fBLZ4_byte\fP * \fBdictionary\fP"
.br
.ti -1c
.RI "const \fBLZ4_stream_t_internal\fP * \fBdictCtx\fP"
.br
.ti -1c
.RI "\fBLZ4_u32\fP \fBdictSize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBLZ4_u32\fP LZ4_stream_t_internal::currentOffset"

.SS "const \fBLZ4_stream_t_internal\fP* LZ4_stream_t_internal::dictCtx"

.SS "const \fBLZ4_byte\fP* LZ4_stream_t_internal::dictionary"

.SS "\fBLZ4_u32\fP LZ4_stream_t_internal::dictSize"

.SS "\fBLZ4_u32\fP LZ4_stream_t_internal::hashTable[\fBLZ4_HASH_SIZE_U32\fP]"

.SS "\fBLZ4_u32\fP LZ4_stream_t_internal::tableType"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
