.TH "LZ4_streamDecode_u" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LZ4_streamDecode_u
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lz4\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long long \fBtable\fP [\fBLZ4_STREAMDECODESIZE_U64\fP]"
.br
.ti -1c
.RI "\fBLZ4_streamDecode_t_internal\fP \fBinternal_donotuse\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBLZ4_streamDecode_t_internal\fP LZ4_streamDecode_u::internal_donotuse"

.SS "unsigned long long LZ4_streamDecode_u::table[\fBLZ4_STREAMDECODESIZE_U64\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
