.TH "source/main.c" 3 "Fri May 6 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <raylib\&.h>\fP
.br
\fC#include 'logger\&.h'\fP
.br
\fC#include 'SceneManager\&.h'\fP
.br
\fC#include 'Scene/SceneSplashScreen\&.h'\fP
.br
\fC#include 'raylib\-extra/raygui\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAYGUI_IMPLEMENTATION\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAYGUI_IMPLEMENTATION"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
