.TH "Resource_t" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resource_t \- The Resource Data Structure:  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResourceManager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [100]"
.br
.RI "Key value for the HashMap\&. "
.ti -1c
.RI "\fBResourceType\fP \fBtype\fP"
.br
.RI "The Resource Type\&. "
.ti -1c
.RI "char \fBpath\fP [100]"
.br
.RI "The Resource file path\&. "
.ti -1c
.RI "\fBResource_u\fP \fBdata\fP"
.br
.RI "The Resource data union\&. "
.ti -1c
.RI "\fBUT_hash_handle\fP \fBhh\fP"
.br
.RI "Hash handler for the uthash library\&. "
.in -1c
.SH "Detailed Description"
.PP 
The Resource Data Structure: 
.SH "Field Documentation"
.PP 
.SS "\fBResource_u\fP Resource_t::data"

.PP
The Resource data union\&. 
.SS "\fBUT_hash_handle\fP Resource_t::hh"

.PP
Hash handler for the uthash library\&. 
.SS "char Resource_t::name[100]"

.PP
Key value for the HashMap\&. 
.SS "char Resource_t::path[100]"

.PP
The Resource file path\&. 
.SS "\fBResourceType\fP Resource_t::type"

.PP
The Resource Type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
