.TH "Resource_u" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resource_u \- The Resource data union (all the possible resource data types)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResourceManager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Image \fBImage\fP"
.br
.ti -1c
.RI "Texture2D \fBTexture2D\fP"
.br
.ti -1c
.RI "Font \fBFont\fP"
.br
.ti -1c
.RI "Wave \fBWave\fP"
.br
.ti -1c
.RI "Sound \fBSound\fP"
.br
.ti -1c
.RI "Music \fBMusic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Resource data union (all the possible resource data types) 
.SH "Field Documentation"
.PP 
.SS "Font Resource_u::Font"

.PP
\fBSee also\fP
.RS 4
\fBFont\fP 
.RE
.PP

.SS "Image Resource_u::Image"

.PP
\fBSee also\fP
.RS 4
\fBImage\fP 
.RE
.PP

.SS "Music Resource_u::Music"

.PP
\fBSee also\fP
.RS 4
\fBMusic\fP 
.RE
.PP

.SS "Sound Resource_u::Sound"

.PP
\fBSee also\fP
.RS 4
\fBSound\fP 
.RE
.PP

.SS "Texture2D Resource_u::Texture2D"

.PP
\fBSee also\fP
.RS 4
\fBTexture2D\fP 
.RE
.PP

.SS "Wave Resource_u::Wave"

.PP
\fBSee also\fP
.RS 4
\fBWave\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
