.TH "ResourceManager_t" 3 "Tue May 10 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceManager_t \- The resource object structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResourceManager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBInit\fP )()"
.br
.ti -1c
.RI "int(* \fBAddResource\fP )(\fBResourceType\fP type, const char *name, const char *path)"
.br
.ti -1c
.RI "int(* \fBRemoveResource\fP )(\fBResourceType\fP type, const char *name)"
.br
.ti -1c
.RI "int(* \fBLoad\fP )()"
.br
.ti -1c
.RI "void *(* \fBGet\fP )(\fBResourceType\fP type, const char *name)"
.br
.ti -1c
.RI "int(* \fBUnload\fP )()"
.br
.ti -1c
.RI "int(* \fBDestroy\fP )()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The resource object structure\&. 
.SH "Field Documentation"
.PP 
.SS "int(* ResourceManager_t::AddResource) (\fBResourceType\fP type, const char *name, const char *path)"

.PP
\fBSee also\fP
.RS 4
\fBResourceManagerAddResource(ResourceType type, const char* name, const char* path)\fP 
.RE
.PP

.SS "int(* ResourceManager_t::Destroy) ()"

.PP
\fBSee also\fP
.RS 4
\fBResourceManagerDestroy()\fP 
.RE
.PP

.SS "void *(* ResourceManager_t::Get) (\fBResourceType\fP type, const char *name)"

.PP
\fBSee also\fP
.RS 4
\fBResourceManagerGet(ResourceType type, const char* name)\fP 
.RE
.PP

.SS "int(* ResourceManager_t::Init) ()"

.PP
\fBSee also\fP
.RS 4
\fBResourceManagerInit()\fP 
.RE
.PP

.SS "int(* ResourceManager_t::Load) ()"

.PP
\fBSee also\fP
.RS 4
\fBResourceManagerLoad()\fP 
.RE
.PP

.SS "int(* ResourceManager_t::RemoveResource) (\fBResourceType\fP type, const char *name)"

.PP
\fBSee also\fP
.RS 4
ResourceManagerRemoveResource(Resource type, const char* name) 
.RE
.PP

.SS "int(* ResourceManager_t::Unload) ()"

.PP
\fBSee also\fP
.RS 4
\fBResourceManagerUnload()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
