.TH "SceneManagerAttribute_t" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneManagerAttribute_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SceneManager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBScene_t\fP * \fBmap\fP"
.br
.ti -1c
.RI "struct \fBScene_t\fP * \fBcurrentScene\fP"
.br
.ti -1c
.RI "struct \fBScene_t\fP * \fBnextScene\fP"
.br
.ti -1c
.RI "bool \fBisSceneEnded\fP"
.br
.ti -1c
.RI "float \fBfixedStepTimer\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBScene_t\fP* SceneManagerAttribute_t::currentScene"

.SS "float SceneManagerAttribute_t::fixedStepTimer"

.SS "bool SceneManagerAttribute_t::isSceneEnded"

.SS "struct \fBScene_t\fP* SceneManagerAttribute_t::map"

.SS "struct \fBScene_t\fP* SceneManagerAttribute_t::nextScene"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
