.TH "include/Scene/SceneLoadScreen.h" 3 "Fri May 6 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Scene/SceneLoadScreen.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SceneManager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSceneLoadScreenOnInit\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneLoadScreenOnStart\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneLoadScreenOnUpdate\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneLoadScreenOnFixedUpdate\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneLoadScreenOnRender\fP (void **_$)"
.br
.ti -1c
.RI "void \fBSceneLoadScreenOnExit\fP (void **_$)"
.br
.ti -1c
.RI "\fBDefineScene\fP (SceneLoadScreen, 'SceneLoadScreen', SceneLoadScreenOnInit, \fBSceneLoadScreenOnStart\fP, \fBSceneLoadScreenOnUpdate\fP, \fBSceneLoadScreenOnFixedUpdate\fP, \fBSceneLoadScreenOnRender\fP, \fBSceneLoadScreenOnExit\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DefineScene (SceneLoadScreen, 'SceneLoadScreen', \fBSceneLoadScreenOnInit\fP, \fBSceneLoadScreenOnStart\fP, \fBSceneLoadScreenOnUpdate\fP, \fBSceneLoadScreenOnFixedUpdate\fP, \fBSceneLoadScreenOnRender\fP, \fBSceneLoadScreenOnExit\fP)"

.SS "void SceneLoadScreenOnExit (void ** _$)"

.SS "void SceneLoadScreenOnFixedUpdate (void ** _$)"

.SS "void SceneLoadScreenOnInit (void ** _$)"

.SS "void SceneLoadScreenOnRender (void ** _$)"

.SS "void SceneLoadScreenOnStart (void ** _$)"

.SS "void SceneLoadScreenOnUpdate (void ** _$)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
