.TH "SceneManager_t" 3 "Tue May 10 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneManager_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SceneManager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSceneManagerAttribute_t\fP \fBattr\fP"
.br
.ti -1c
.RI "int(* \fBInit\fP )()"
.br
.ti -1c
.RI "int(* \fBRegister\fP )(const char *name, struct \fBScene_t\fP *scene)"
.br
.ti -1c
.RI "int(* \fBStart\fP )(const char *firstSceneName)"
.br
.ti -1c
.RI "double(* \fBTime\fP )()"
.br
.ti -1c
.RI "int(* \fBNext\fP )(const char *name)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBSceneManagerAttribute_t\fP SceneManager_t::attr"

.SS "int(* SceneManager_t::Init) ()"

.SS "int(* SceneManager_t::Next) (const char *name)"

.SS "int(* SceneManager_t::Register) (const char *name, struct \fBScene_t\fP *scene)"

.SS "int(* SceneManager_t::Start) (const char *firstSceneName)"

.SS "double(* SceneManager_t::Time) ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
