.TH "include/SceneManager/Scenes/SceneSplashScreen.h" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/SceneManager/Scenes/SceneSplashScreen.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SceneManager/Scene\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSceneSplashScreenStart\fP ()"
.br
.ti -1c
.RI "void \fBSceneSplashScreenUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSceneSplashScreenFixedUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSceneSplashScreenRender\fP ()"
.br
.ti -1c
.RI "void \fBSceneSplashScreenExit\fP ()"
.br
.ti -1c
.RI "\fBDefineScene\fP (SceneSplashScreen, 'SceneSplashScreen', SceneSplashScreenStart, \fBSceneSplashScreenUpdate\fP, \fBSceneSplashScreenFixedUpdate\fP, \fBSceneSplashScreenRender\fP, \fBSceneSplashScreenExit\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DefineScene (SceneSplashScreen, 'SceneSplashScreen', \fBSceneSplashScreenStart\fP, \fBSceneSplashScreenUpdate\fP, \fBSceneSplashScreenFixedUpdate\fP, \fBSceneSplashScreenRender\fP, \fBSceneSplashScreenExit\fP)"

.SS "void SceneSplashScreenExit ()"

.SS "void SceneSplashScreenFixedUpdate ()"

.SS "void SceneSplashScreenRender ()"

.SS "void SceneSplashScreenStart ()"

.SS "void SceneSplashScreenUpdate ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
