.TH "source/SceneManager/SceneManager.c" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/SceneManager/SceneManager.c
.SH SYNOPSIS
.br
.PP
\fC#include 'SceneManager/SceneManager\&.h'\fP
.br
\fC#include 'utils/logger\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCENE_MANAGER_PREFIX\fP   \fBLOG_COLOR_YELLOW\fP '[SceneManager] ' LOG_COLOR_RESET"
.br
.ti -1c
.RI "#define \fBSCENE_MANAGER_FIXED_TIME_STEP\fP   (1\&.0f / 2\&.0f)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBSceneManagerInit\fP ()"
.br
.ti -1c
.RI "int \fBSceneManagerRegister\fP (const char *name, struct \fBScene_t\fP *scene)"
.br
.ti -1c
.RI "int \fBSceneManagerStart\fP (const char *firstSceneName)"
.br
.ti -1c
.RI "double \fBSceneManagerTime\fP ()"
.br
.ti -1c
.RI "int \fBSceneManagerNext\fP (const char *name)"
.br
.ti -1c
.RI "int \fBSceneManagerLoop\fP ()"
.br
.ti -1c
.RI "int \fBSceneManagerEnd\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SCENE_MANAGER_FIXED_TIME_STEP   (1\&.0f / 2\&.0f)"

.SS "#define SCENE_MANAGER_PREFIX   \fBLOG_COLOR_YELLOW\fP '[SceneManager] ' LOG_COLOR_RESET"

.SH "Function Documentation"
.PP 
.SS "int SceneManagerEnd ()"

.SS "int SceneManagerInit ()"

.SS "int SceneManagerLoop ()"

.SS "int SceneManagerNext (const char * name)"

.SS "int SceneManagerRegister (const char * name, struct \fBScene_t\fP * scene)"

.SS "int SceneManagerStart (const char * firstSceneName)"

.SS "double SceneManagerTime ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
