.TH "source/utils/stringutils.c" 3 "Tue May 10 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/utils/stringutils.c
.SH SYNOPSIS
.br
.PP
\fC#include 'utils/stringutils\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBStringLimit\fP (char *string, size_t maxlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void StringLimit (char * string, size_t maxlen)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
