.TH "include/utils/stringutils.h" 3 "Tue May 10 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/utils/stringutils.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBStringLength\fP (char *string, size_t maxlen)"
.br
.ti -1c
.RI "void \fBStringLimit\fP (char *string, size_t maxlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t StringLength (char * string, size_t maxlen)"

.SS "void StringLimit (char * string, size_t maxlen)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
