.TH "User_t" 3 "Tue May 10 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <User\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBusername\fP [\fBUSER_USERNAME_MAX_LEN\fP+1]"
.br
.ti -1c
.RI "char \fBpassword\fP [\fBUSER_PASSWORD_MAX_LEN\fP+1]"
.br
.ti -1c
.RI "UT_hash_handle \fBhh\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "UT_hash_handle User_t::hh"

.SS "char User_t::password[\fBUSER_PASSWORD_MAX_LEN\fP+1]"

.SS "char User_t::username[\fBUSER_USERNAME_MAX_LEN\fP+1]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
