.TH "UT_array" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UT_array
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utarray\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBi\fP"
.br
.ti -1c
.RI "unsigned \fBn\fP"
.br
.ti -1c
.RI "\fBUT_icd\fP \fBicd\fP"
.br
.ti -1c
.RI "char * \fBd\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* UT_array::d"

.SS "unsigned UT_array::i"

.SS "\fBUT_icd\fP UT_array::icd"

.SS "unsigned UT_array::n"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
