.TH "UT_icd" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UT_icd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utarray\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsz\fP"
.br
.ti -1c
.RI "\fBinit_f\fP * \fBinit\fP"
.br
.ti -1c
.RI "\fBctor_f\fP * \fBcopy\fP"
.br
.ti -1c
.RI "\fBdtor_f\fP * \fBdtor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBctor_f\fP* UT_icd::copy"

.SS "\fBdtor_f\fP* UT_icd::dtor"

.SS "\fBinit_f\fP* UT_icd::init"

.SS "size_t UT_icd::sz"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
