.TH "UT_string" 3 "Sun May 8 2022" "Ruba Mazzetto" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UT_string
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utstring\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBd\fP"
.br
.ti -1c
.RI "size_t \fBn\fP"
.br
.ti -1c
.RI "size_t \fBi\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* UT_string::d"

.SS "size_t UT_string::i"

.SS "size_t UT_string::n"


.SH "Author"
.PP 
Generated automatically by Doxygen for Ruba Mazzetto from the source code\&.
